# Generated by Django 5.1.13 on 2025-10-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion_tarea',
            old_name='obsevaciones',
            new_name='observaciones',
        ),
    ]
